A-an
DarcyManoel/Endless-Sky-Constellations pull request #7
Opened 2024-06-07 12:46 UTC by TheGiraffe3

Fixes a bug I forgot to change in #6 by changing an an to an a.

2024-06-07 12:49 UTC, Lorantine commented
Wait a few hours and I'll take a look at the rest of #6.
My work ends in 2,5 hours.
In case I find more, you can then add that as well.

2024-06-07 17:37 UTC, TheGiraffe3 commented
@Lorantine does this now resolve most of your suggested changes in #6?

2024-06-07 17:42 UTC, TheGiraffe3 commented
> 'You might want to add "Small Scale Delivery" to disable repeatable spaceport missions. That's the kor efret mission that gives 1000 credits and pops up regularly.'

@DarcyManoel would you like me to do that in this PR, or it to be done in a different one?

2024-06-07 18:39 UTC, Lorantine commented
> @Lorantine in #6:
> 
> > You might want to add "Small Scale Delivery" to disable repeatable spaceport missions. That's the kor efret mission that gives 1000 credits and pops up regularly.
> 
> @DarcyManoel would you like me to do that in this PR, or it to be done in a different one?

Just do a separate one, better overview and such. Thank you in advance!

2024-06-07 18:46 UTC, Lorantine requested changes
Last small batch of to-fix items.

The rest looks fine; great work.

2024-06-07 18:46 UTC, Lorantine commented on data/irm/missions/2 appropriation.txt
> +	description `David is wary about the Quarg, insisting that you should inform them about your venture before they discover it for themselves. Any warning that the Quarg might offer you is important t
With the removal of "as much", that part feels less like a stand-alone sentence, and now more just ap art of the former one. As such, the semicolon should be a comma.

2024-06-07 18:46 UTC, Lorantine commented on data/irm/missions/2 appropriation.txt
> +			`	A message on David's communicator reports that two Quarg Wardragons have entered the system. He hastily calls you to meet him at your ship and meet them.`
Double usage of "meet" may be a bit confusing.
Perhaps an altered version (it's a tricky sentence in general, admittedly): "He hastily calls you to meet him at your ship, urging for the two of you to meet the Quarg ships."
Or something like that.

2024-06-07 18:46 UTC, Lorantine commented on data/irm/missions/2 appropriation.txt
> +			`	"Not me personally, but of course we need help throughout the entire operation. I'm currently not as involved with the specifics of any one area, but we have two major departments here; being de
The word "being" can go too.

2024-06-08 00:31 UTC, DarcyManoel requested changes
A few of your changes reverse changes made in #6, why is that?

2024-06-08 00:31 UTC, DarcyManoel commented on data/irm/missions/2 appropriation.txt
> +			`	"It looks like we have the opportunity to establish our station here, and possibly even maintain a colony under our purview," David says, taking a breath before his next statement. "On a ringwor
`like the Quarg own` -> `like the Quarg's own`

2024-06-08 00:31 UTC, DarcyManoel commented on data/irm/missions/2 appropriation.txt
> +	description `David is wary about the Quarg, insisting that you should inform them about your venture before they discover it for themselves. Any warning that the Quarg might offer you is important t
I agree.

2024-06-08 00:31 UTC, DarcyManoel commented on data/irm/missions/2 appropriation.txt
> +			`	A message on David's communicator reports that two Quarg Wardragons have entered the system. He hastily calls you to meet him at your ship and meet them.`
I agree that the sentence should be changed to avoid that repetition.

2024-06-08 00:31 UTC, DarcyManoel commented on data/irm/missions/2 appropriation.txt
> +			`	"Not me personally, but of course we need help throughout the entire operation. I'm currently not as involved with the specifics of any one area, but we have two major departments here; being de
Agreed, though I'm not sure why we're removing the `one`s again, they were added in #6.

2024-06-08 01:05 UTC, Lorantine commented on data/irm/missions/2 appropriation.txt
> +			`	"It looks like we have the opportunity to establish our station here, and possibly even maintain a colony under our purview," David says, taking a breath before his next statement. "On a ringwor
I don't think so; it's a ringworld, that the Quarg species owns, and it's established that the plural of Quarg is also Quarg. Same as it'd be "like the Hai own" vs "like the Hais own".
And with the apostrophe, 'Quarg's' would translate to 'Quarg its', which is grammatically incorrect.
So I believe the way it was done, is the correct version.

2024-06-08 01:09 UTC, Lorantine commented on data/irm/missions/2 appropriation.txt
> +			`	"Not me personally, but of course we need help throughout the entire operation. I'm currently not as involved with the specifics of any one area, but we have two major departments here; being de
The only difference as-is compared to how it was before that PR, is that the comma is now a semicolon. My requested change would also remove a word.
It's shorter and reads easier, especially due to avoiding repetition of the word "one", which will become redundant due to the sentence structure once my small suggestion is incorporated.
So in short; because they're no longer needed, in favour of a nicer sentence flow.

2024-06-08 02:55 UTC, TheGiraffe3 commented
Because @Lorantine wasn’t sure they read well and reviewed a whole bunch after the merge of #6. Most of the suggested changes were accurate.

2024-06-08 03:15 UTC, DarcyManoel approved these changes

2024-06-08 15:58 UTC, TheGiraffe3 commented
@Lorantine would you re-review this?

2024-06-09 07:09 UTC, merged

2024-06-09 11:44 UTC, Lorantine reviewed
Looks fine.

2024-06-09 11:48 UTC, TheGiraffe3 commented
Great.